export const MODE_CHANGE = 'MODE_CHANGE';
export const BACKGROUND_LAFALDZ_GANJIL = 'BACKGROUND_LAFALDZ_GANJIL';
export const BACKGROUND_LAFALDZ_GENAP = 'BACKGROUND_LAFALDZ_GENAP';
export const TEXT_LAFALDZ = 'TEXT_LAFALDZ';
